- name: Cisco IOS Commands
  hosts: ios
  gather_facts: no
  connection: network_cli
  vars:
    ansible_ssh_host: '{{ ip_address }}'
    ansible_network_os: "{{ ansible_network_os_override | default('cisco.ios.ios') }}"
    ansible_command_timeout: 120
    output_path: "{{ playbook_dir }}/csv"
    filename: "network_device_info_{{ date }}.csv"
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: inventory/host_vars/show_ip_ospf_nei.json
        name: show_ip_ospf_neighbor

    - name: Debug Test Var
      ansible.builtin.debug: 
        msg: "{{ show_ip_ospf_neighbor.stdout_lines | flatten | reject('match', 'Load') | reject('match', 'Time') | select() | list | map('regex_replace', '^(.*\\w+/\\w*?)\\s+-\\s+(.*)$', '\\1 \\2') | map('regex_replace', '(/\\s+|\\s\\s+)', ',') | list }}"
      run_once: True
